FootballWorldWeb/Areas/UserPanel/Controllers/MatchesController.cs
using CsvHelper;
using CsvHelper.Configuration;
using FootballWorld.Data;
using FootballWorldWeb.Areas.UserPanel.Models;
using FootballWorldWeb.Data;
using FootballWorldWeb.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FootballWorldWeb.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class MatchesController : Controller
    {
        private readonly FootballDbContext dbContext;
        private readonly StandingsCalculatorService standingsCalculatorService;
        public MatchesController(FootballDbContext dbContext, StandingsCalculatorService standingsCalculatorService)
        {
            this.dbContext = dbContext;
            this.standingsCalculatorService = standingsCalculatorService;
        }

        public IActionResult Index(int groupId = 0)
        {
            if (groupId < 1)
            {
                TempData["Error"] = "Please provide ID greater than 0";
                return RedirectToAction("Index", "Home");
            }
            MatchesIndexViewModel viewModel = new MatchesIndexViewModel();
            Group group = dbContext.Groups.Include(x => x.Season).ThenInclude(x => x.Competition).Where(x => x.Id == groupId).FirstOrDefault();
            if (group == null) { return new ContentResult() { StatusCode = 404, Content = "Group with ID #" + groupId + " wasn't found." }; }
            ViewData["Title"] = String.Format("List of Matches for {0} of {1} ({2})",
                group.Name,
                group.Season.Competition.Name,
                group.Season.Name);
            IQueryable<Match> query;

            query = dbContext.Matches.Where(x => x.GroupId == groupId).Include(x => x.Results).ThenInclude(x => x.Team).OrderBy(x => x.Start);

            List<Match> matches = query.ToList();
            viewModel.Matches = matches;
            viewModel.GroupId = groupId;
            viewModel.SeasonId = group.SeasonId;
            return View(viewModel);
        }

        public IActionResult Create(int groupId = 0)
        {
            ViewData["Title"] = "Create a Match";
            MatchFormViewModel viewModel = new MatchFormViewModel();

            Group group = dbContext.Groups.Where(x => x.Id == groupId).Include(x => x.Season).FirstOrDefault();
            if (group == null) { return new NotFoundResult(); }
            viewModel.HomeTeamSelect = new SelectList(
            dbContext.GroupTeams.Where(x => x.GroupId == groupId).Select(x => x.Team).OrderBy(x => x.Name).ToList(),
            "Id", "Name");
            viewModel.AwayTeamSelect = new SelectList(
                dbContext.GroupTeams.Where(x => x.GroupId == groupId).Select(x => x.Team).OrderBy(x => x.Name).ToList()
                , "Id", "Name");

            viewModel.GroupId = group.Id;
            viewModel.Start = new DateTime(group.Season.StartYear, 9, 1, 20, 00, 00);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(MatchFormViewModel formData)
        {
            if (formData.HomeResult.Team.Id == formData.AwayResult.Team.Id)
            {
                TempData["Error"] = "Home and Away team can't be the same.";
                return RedirectToAction("Create", new { groupId = formData.GroupId });
            }
            Match match = new Match()
            {
                Start = formData.Start,
                Finished = formData.Finished,
                GroupId = formData.GroupId,
            };
            if (formData.Comments != null)
            {
                match.Comments = formData.Comments.Trim();
            }
            dbContext.Add(match);
            dbContext.SaveChanges();

            MatchResult homeResult = new MatchResult()
            {
                Score = formData.HomeResult.Score,
                TeamId = formData.HomeResult.Team.Id,
                Type = MatchResultType.HomeTeam,
                MatchId = match.Id
            };
            MatchResult awayResult = new MatchResult()
            {
                Score = formData.AwayResult.Score,
                TeamId = formData.AwayResult.Team.Id,
                Type = MatchResultType.AwayTeam,
                MatchId = match.Id
            };
            List<MatchResult> results = new List<MatchResult>() { homeResult, awayResult };
            dbContext.MatchResults.AddRange(results);
            dbContext.SaveChanges();
            standingsCalculatorService.UpdateDbStandings(formData.GroupId);
            return RedirectToAction("Edit", new { id = match.Id, groupId = match.GroupId });
        }


        [HttpGet]
        public IActionResult Edit(int id, int? groupId)
        {
            if (id < 0 & groupId == null)
            {
                TempData["Error"] = "You must provide both match Id and group Id";
                return RedirectToAction("Index", "Home");
            }
            ViewData["Title"] = "Edit Match";

            Match match = dbContext.Matches
                .Include(x => x.Results)
                .ThenInclude(x => x.Team)
                .Where(x => x.Id == id)
                .Where(x => x.GroupId == groupId).FirstOrDefault();

            if (match == null) { return new NotFoundResult(); }
            MatchFormViewModel viewModel = new MatchFormViewModel();

            viewModel.Id = match.Id;
            viewModel.Start = match.Start;
            viewModel.Finished = match.Finished;
            viewModel.GroupId = match.GroupId;
            viewModel.Comments = match.Comments;
            viewModel.HomeResult = match.Results.Where(x => x.Type == MatchResultType.HomeTeam).FirstOrDefault();
            viewModel.AwayResult = match.Results.Where(x => x.Type == MatchResultType.AwayTeam).FirstOrDefault();

            viewModel.HomeTeamSelect = new SelectList(
                dbContext.GroupTeams.Include(x => x.Team).Where(x => x.GroupId == groupId).Select(x => x.Team).OrderBy(x => x.Name).ToList(),
                "Id", "Name", viewModel.HomeResult.Team.Id);
            viewModel.AwayTeamSelect = new SelectList(
                dbContext.GroupTeams.Include(x => x.Team).Where(x => x.GroupId == groupId).Select(x => x.Team).OrderBy(x => x.Name).ToList(), "Id", "Name", viewModel.AwayResult.Team.Id);

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(int id, MatchFormViewModel formData)
        {
            Match match = dbContext.Matches.Where(x => x.Id == id).FirstOrDefault();
            if (match == null)
            {
                return new NotFoundResult();
            }
            MatchResult homeResult = dbContext.MatchResults
                .Where(x => x.Match == match)
                .Where(x => x.Type == MatchResultType.HomeTeam).FirstOrDefault();
            MatchResult awayResult = dbContext.MatchResults
                .Where(x => x.Match == match)
                .Where(x => x.Type == MatchResultType.AwayTeam).FirstOrDefault();

            match.Finished = formData.Finished;
            match.Start = formData.Start;

            homeResult.Score = formData.HomeResult.Score;
            homeResult.TeamId = formData.HomeResult.Team.Id;

            awayResult.Score = formData.AwayResult.Score;
            awayResult.TeamId = formData.AwayResult.Team.Id;

            if (formData.Comments != null)
            {
                match.Comments = formData.Comments.Trim();
            }
            dbContext.SaveChanges();

            standingsCalculatorService.UpdateDbStandings(match.GroupId);

            return RedirectToAction("Edit", new { id = id, groupId = match.GroupId });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (id < 1) { return new BadRequestResult(); }
            Match match = dbContext.Matches.Where(x => x.Id == id).FirstOrDefault();
            if (match == null)
            {
                return new NotFoundResult();
            }

            dbContext.Matches.Remove(match);
            dbContext.SaveChanges();
            standingsCalculatorService.UpdateDbStandings(match.GroupId);
            return RedirectToAction("Index", new { groupId = match.GroupId });
        }


        public IActionResult Import(int groupId)
        {
            ViewData["Title"] = "Import Matches using a file";
            ImportFormViewModel viewModel = new ImportFormViewModel();
            viewModel.RelationshipId = groupId;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult ImportPreview(ImportFormViewModel formData)
        {
            ViewData["Title"] = "Preview of imported file";
            ImportPreviewViewModel<Match> viewModel = new ImportPreviewViewModel<Match>();
            viewModel.RelationshipId = formData.RelationshipId;
            //parse file and pass it to viewmodel//
            CsvConfiguration csvConfig = new CsvConfiguration(CultureInfo.InvariantCulture) { HasHeaderRecord = true, IgnoreBlankLines = true };
            using (var reader = new StreamReader(formData.UploadedFile.OpenReadStream()))
            using (var csv = new CsvReader(reader, csvConfig))
            {
                var records = csv.GetRecords<CsvMatch>();
                foreach (CsvMatch csvMatch in records)
                {
                    var filledRow = csvMatch.GetType().GetProperties()
                            .All(p => p.GetValue(csvMatch) != null);
                    
                    if(!filledRow) { continue; }
                    Team homeTeam = dbContext.Teams.Where(x => x.Name == csvMatch.HomeTeam).FirstOrDefault();
                    Team awayTeam = dbContext.Teams.Where(x => x.Name == csvMatch.AwayTeam).FirstOrDefault();

FootballWorldWeb/Controllers/SeasonsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Data;
using FootballWorldWeb.Models.Competitions;
using FootballWorldWeb.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FootballWorldWeb.Controllers
{
    public class SeasonsController : Controller
    {
        private readonly ILogger<SeasonsController> _logger;
        private readonly FootballDbContext dbContext;
        private readonly StandingsCalculatorService standingsCalculator;

        public SeasonsController(ILogger<SeasonsController> logger,
            FootballDbContext dbContext, StandingsCalculatorService standingsCalculator)
        {
            _logger = logger;
            this.dbContext = dbContext;
            this.standingsCalculator = standingsCalculator;
        }

        public IActionResult Details(int id,string slug)
        {
            Season season = dbContext.Seasons
                .Include(c => c.Competition)
                .Include(g => g.Groups)
                .ThenInclude(g=>g.GroupTeams).ThenInclude(t=>t.Team)
                .Include(g=>g.Groups)
                .ThenInclude(g => g.Standings)
                .ThenInclude(s => s.Items).ThenInclude(t => t.Team)
                    .Include(g => g.Groups)
                    .ThenInclude(g => g.Matches).ThenInclude(t=>t.Results).ThenInclude(t=>t.Team)
                    .Where(x => x.Id == id)
                    .FirstOrDefault();
                if (season == null) { return new NotFoundResult(); }
                SeasonViewViewModel viewModel = new SeasonViewViewModel();
                viewModel.Season = season;
                viewModel.Competition = season.Competition;
                viewModel.Groups = season.Groups;
                viewModel.SingleGroup = season.Groups.Count > 1 ? false : true;
            viewModel.Lists = season.Groups.Where(x => x.GroupType == GroupType.TeamsList).ToList();
                ViewData["Title"] = String.Format("Season {0} of {1}", viewModel.Season.Name, viewModel.Competition.Name);

                return View(viewModel);
                //todo create view for seasonview//
            }
        }
    }

FootballWorldWeb/Areas/UserPanel/Views/Matches/Create.cshtml
@model MatchFormViewModel
    <div class="row">
        <div class="col">
            <p>
                <a asp-action="Index" asp-route-groupId="@Model.GroupId">Back</a>

            </p>
            <h2>@ViewData["Title"]</h2>
            <form asp-area="UserPanel" asp-controller="Matches" asp-action="Create" method="post">
                <input type="hidden" asp-for="GroupId" />

                <div class="row">
                    <div class="col">

                        <select class="form-control" asp-for="HomeResult.Team.Id" asp-items="@Model.HomeTeamSelect">
                        </select>
                        <hr />
                        <div class="form-group">
                            <input asp-for="@Model.HomeResult.Score" class="form-control" />
                        </div>
                    </div>
                    <div class="col">
                        <select class="form-control" asp-for="AwayResult.Team.Id" asp-items="@Model.AwayTeamSelect">
                        </select>
                        <hr />
                        <div class="form-group">
                            <input asp-for="@Model.AwayResult.Score" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group" id="dateTimePicker">
                            <input id="matchStart" type="datetime" asp-for="Start" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label class="label" asp-for="Finished">
                                Finished:
                                <input type="checkbox" asp-for="Finished" />
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label class="label">Extra notes</label>
                            <textarea class="form-control" asp-for="Comments"></textarea>
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>

                </div>
            </form>
        </div>
    </div> 

@section Scripts {
    <script>

        $(document).ready(function () {
            $("#matchStart").flatpickr({
                enableTime: true,
                dateFormat: "Y-m-d H:i",
            });
        })
    </script>
}

FootballWorldWeb/Areas/UserPanel/Views/Matches/Edit.cshtml
@model MatchFormViewModel
<div class="row">
    <div class="col">
        <p>
            <a asp-action="Index" asp-route-groupId="@Model.GroupId">Back</a>

        </p>
        <h2>@ViewData["Title"]</h2>
        <form asp-area="UserPanel" asp-controller="Matches" asp-action="Edit" asp-route-id="@Model.Id" method="post">
            <div class="row">
                <div class="col">

                    <select class="form-control" asp-for="HomeResult.Team.Id" asp-items="@Model.HomeTeamSelect">
                    </select>
                    <hr />
                    <div class="form-group">
                        <input asp-for="@Model.HomeResult.Score" class="form-control" />
                    </div>
                </div>
                <div class="col">
                    <select class="form-control" asp-for="AwayResult.Team.Id" asp-items="@Model.AwayTeamSelect">
                    </select>
                    <hr />
                    <div class="form-group">
                        <input asp-for="@Model.AwayResult.Score" class="form-control" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <input type="datetime" id="matchStart" asp-for="Start" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="label" asp-for="Finished">
                            Finished:
                            <input type="checkbox" asp-for="Finished" />
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label class="label">Extra notes</label>
                        <textarea class="form-control" asp-for="Comments"></textarea>
                    </div>

                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-action="Create" asp-route-groupId="@Model.GroupId" class="btn btn-outline-secondary">Add New</a>
        </form>
        <hr />
        <div class="row">
            <div class="col">
                <form onsubmit="return confirm('Are you sure?')" asp-action="Delete" asp-route-id="@Model.Id" method="post">
                    <button class="btn btn-danger">
                        Delete
                    </button>
                </form>
            </div>
        </div>
        
    </div>
</div>

@section Scripts {
    <script>

        $(document).ready(function () {
            $("#matchStart").flatpickr({
                enableTime: true,
                dateFormat: "Y-m-d H:i",
            });
        })
    </script>
}

FootballWorldWeb/Areas/UserPanel/Views/Matches/Import.cshtml
@model ImportFormViewModel
<div class="row">
    <div class="col">
        <h2>@ViewData["Title"]</h2>
        <div class="alert alert-info">
           You can import matches using this form. Max number of matches is 20. You can't import stats and
            other details.  
        </div>
        <form enctype="multipart/form-data"
              asp-area="UserPanel"
              asp-controller="Matches"
              asp-action="ImportPreview"
              method="post">
            <div class="form-group">
                <label class="label" asp-for="UploadedFile">
                    Select File
                </label>
                <input type="file" asp-for="UploadedFile" class="form-control" />
                <input type="hidden" asp-for="RelationshipId" class="form-control" />

            </div>

            <button class="btn btn-primary">
                Import
            </button>
            <a asp-action="Index" class="btn btn-outline-secondary">Back</a>
        </form>
    </div>
</div>

FootballWorldWeb/Areas/UserPanel/Views/Matches/ImportPreview.cshtml
@model ImportPreviewViewModel<FootballWorld.Data.Match>

    <div>
        <div class="row">
            <div class="col">
                <h2> @ViewData["Title"]</h2>

                <div class="row">
                    <div class="col">
                        <p>These matches are imported</p>
                        <table class="table">
                            @foreach (var match in Model.Items)
                            {
                                <tr>
                                    <td>
                                    @String.Format("{0}-{1}",
                                   match.GetHomeResult().Team.Name,
                                   @match.GetAwayResult().Team.Name)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="row">
           
        </div>
    </div>

FootballWorldWeb/Areas/UserPanel/Views/Matches/Index.cshtml
@model MatchesIndexViewModel


<div class="row">
    <div class="col">
        <a asp-controller="Seasons" asp-action="Overview" asp-route-id="@Model.SeasonId">Back</a>
        <hr />
        <div class="text-left">
            <a asp-action="Create" asp-route-groupId="@Model.GroupId" class="btn btn-xs btn-outline-secondary">Add New</a>
            <a asp-action="Import" asp-route-groupId="@Model.GroupId" class="btn btn-xs btn-outline-secondary">Import</a>

        </div>
        <div class="mt-4">
            <h3>@ViewData["Title"]</h3>
        </div>

        <ul class="list-group">
            @foreach (var match in Model.Matches)
            {
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-8">
                            @if (match.Finished)
                            {<strong>F: </strong>}
                            @String.Format("{0}-{1}",
                           match.Results.Where(x => x.Type == MatchResultType.HomeTeam).FirstOrDefault().Team.Name,
                           match.Results.Where(x => x.Type == MatchResultType.AwayTeam).FirstOrDefault().Team.Name
                           )
                        </div>
                        <div class="col">
                            <a asp-action="Edit" asp-route-id="@match.Id" asp-route-groupId="@match.GroupId">Edit</a>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>