FootballWorldWeb/Controllers/CompetitionsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Data;
using FootballWorldWeb.Models.Competitions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootballWorldWeb.Controllers
{
    public class CompetitionsController : Controller
    {
        private readonly FootballDbContext dbContext;

        public CompetitionsController(FootballDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Overview(int id,string slug)
        {
            Competition competition = dbContext.Competitions.Include(x=>x.Seasons).Where(x => x.Id == id).FirstOrDefault();
            if(competition ==null) { return new NotFoundResult(); }
            ViewData["Title"] = String.Format("{0} - Overview", competition.Name);
            CompetitionOverviewViewModel viewModel = new CompetitionOverviewViewModel();
            viewModel.Name = competition.Name;
            viewModel.Id = competition.Id;
            viewModel.Logo = competition.CompetitionLogo;
            viewModel.Slug = competition.Slug;
            viewModel.Seasons = competition.Seasons;
            return View(viewModel);
        }
       

        public IActionResult GroupView() {
            return View();

        }
    }
}

FootballWorldWeb/Controllers/SeasonsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Data;
using FootballWorldWeb.Models.Competitions;
using FootballWorldWeb.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FootballWorldWeb.Controllers
{
    public class SeasonsController : Controller
    {
        private readonly ILogger<SeasonsController> _logger;
        private readonly FootballDbContext dbContext;
        private readonly StandingsCalculatorService standingsCalculator;

        public SeasonsController(ILogger<SeasonsController> logger,
            FootballDbContext dbContext, StandingsCalculatorService standingsCalculator)
        {
            _logger = logger;
            this.dbContext = dbContext;
            this.standingsCalculator = standingsCalculator;
        }

        public IActionResult Details(int id,string slug)
        {
            Season season = dbContext.Seasons
                .Include(c => c.Competition)
                .Include(g => g.Groups)
                .ThenInclude(g=>g.GroupTeams).ThenInclude(t=>t.Team)
                .Include(g=>g.Groups)
                .ThenInclude(g => g.Standings)
                .ThenInclude(s => s.Items).ThenInclude(t => t.Team)
                    .Include(g => g.Groups)
                    .ThenInclude(g => g.Matches).ThenInclude(t=>t.Results).ThenInclude(t=>t.Team)
                    .Where(x => x.Id == id)
                    .FirstOrDefault();
                if (season == null) { return new NotFoundResult(); }
                SeasonViewViewModel viewModel = new SeasonViewViewModel();
                viewModel.Season = season;
                viewModel.Competition = season.Competition;
                viewModel.Groups = season.Groups;
                viewModel.SingleGroup = season.Groups.Count > 1 ? false : true;
            viewModel.Lists = season.Groups.Where(x => x.GroupType == GroupType.TeamsList).ToList();
                ViewData["Title"] = String.Format("Season {0} of {1}", viewModel.Season.Name, viewModel.Competition.Name);

                return View(viewModel);
                //todo create view for seasonview//
            }
        }
    }

FootballWorldWeb/Areas/UserPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FootballWorldWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/flatpickr/flatpickr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="UserPanel" asp-controller="Home" asp-action="Index">FootballWorldWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link"
                               asp-area="UserPanel"
                               asp-controller="Teams"
                               asp-action="Index">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               asp-area="UserPanel"
                               asp-controller="Matches"
                               asp-action="Index">Matches</a> 
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               asp-area="UserPanel"
                               asp-controller="Competitions"
                               asp-action="Index">Competitions</a>
                        </li><li class="nav-item">
                            <a class="nav-link"
                               asp-area="UserPanel"
                               asp-controller="Seasons"
                               asp-action="Index">Seasons</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if(TempData["Error"] != null)
            {
            <div class="alert alert-danger">
                @TempData["Error"]
            </div>
            }
            @if(TempData["Message"] != null)
            {
        <div class="alert alert-info">
            @TempData["Message"]
        </div>
            } 
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FootballWorldWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/flatpickr/flatpickr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>