FootballWorldWeb/Areas/UserPanel/Controllers/SeasonsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Areas.UserPanel.Models;
using FootballWorldWeb.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FootballWorldWeb.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class SeasonsController : Controller
    {
        private readonly FootballDbContext dbContext;

        public SeasonsController(FootballDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        public IActionResult Overview(int? id)
        {
            if(id==null) {
                TempData["Error"] = "You must provide season ID";
                return RedirectToAction("Home", "Index");
            }
            Season season = dbContext.Seasons
                .Include(x => x.Competition)
                .Include(x => x.Groups)
                .ThenInclude(x => x.GroupTeams)
                .Where(x=>x.Id==id)
                .FirstOrDefault();
            if(season==null) { return new NotFoundResult(); }
            SeasonOverviewViewModel viewModel = new SeasonOverviewViewModel();
            viewModel.Id = (int) id;
            viewModel.Season = season;
            ViewData["Title"] = String.Format("Season Overview {0}", season.Name);
            return View(viewModel);
        }
        public IActionResult Index(int? competitionId)
        {
            if(competitionId == null)
            {
                TempData["Error"] = "You must provide competition ID";
                return RedirectToAction("Index", "Home");
            }
            Competition competition = dbContext.Competitions.Where(x => x.Id == competitionId).FirstOrDefault();
            if(competition == null)
            {
                return new NotFoundResult();
            }

            ViewData["Title"] = "List of Seasons";
            List<Season> seasons = dbContext.Seasons.Where(x=>x.CompetitionId==competitionId).Include(x=>x.Competition).ToList();
            return View(seasons);
        }
        public IActionResult Create(int competitionId)
        {
            Competition competition = dbContext.Competitions.Where(x => x.Id == competitionId).FirstOrDefault();
            if (competition == null)
            {
                return new NotFoundResult();
            }
            ViewData["Title"] = "Create a Season";
            SeasonFormViewModel viewModel = new SeasonFormViewModel();
            viewModel.CompetitionId = competition.Id;
            viewModel.Competition = competition;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Create(SeasonFormViewModel formData)
        {
            Season season = new Season();
            season.Name = formData.Name;
            season.StartYear = formData.StartYear;
            season.EndYear = formData.EndYear;
            season.CompetitionId = formData.CompetitionId;
            string slug = String.Format("{0}-{1}", dbContext.Competitions.Where(x => x.Id == formData.CompetitionId).FirstOrDefault().Name, formData.Name);
            season.Slug = new Slugify.SlugHelper().GenerateSlug(slug);

            dbContext.Seasons.Add(season);
            if(dbContext.SaveChanges()>0)
            {
                return RedirectToAction("Index", new { competitionId = formData.CompetitionId });
            }
            return new BadRequestResult();
        }
        public IActionResult Edit(int id)
        {
            ViewData["Title"] = "Edit Season";
            Season season = dbContext.Seasons.Where(x => x.Id == id).FirstOrDefault();
            if(season==null)
            {
                return new NotFoundResult();
            }
            SeasonFormViewModel viewModel = new SeasonFormViewModel();
            viewModel.Id = season.Id;
            viewModel.Name = season.Name;
            viewModel.StartYear = season.StartYear;
            viewModel.EndYear = season.EndYear;
            return View(viewModel);
                 
        }

        [HttpPost]
        public IActionResult Edit(SeasonFormViewModel formData) {
            Season season = dbContext.Seasons.Include(x => x.Competition).Where(x => x.Id == formData.Id).FirstOrDefault();
            if (season == null) { return new NotFoundResult(); }
            season.Name = formData.Name;
            season.Slug = new Slugify.SlugHelper().GenerateSlug(String.Format("{0}-{1}",season.Competition.Slug,season.Name));
            if (dbContext.SaveChanges() > 0)
            {
                TempData["Message"] = "Success";
                return RedirectToAction("Edit", new { id = season.Id });
            }
            TempData["Error"] = "Error happened.";
            return RedirectToAction("Edit", new { id = season.Id });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Season season = dbContext.Seasons.Where(x => x.Id == id).FirstOrDefault();
            if(season==null) { return new NotFoundResult(); }
            dbContext.Seasons.Remove(season);
            dbContext.SaveChanges();
            return RedirectToAction("Overview", "Competitions",new { id = season.CompetitionId });
        }
    }
}

FootballWorldWeb/Controllers/GroupsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Data;
using FootballWorldWeb.Models.Groups;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootballWorldWeb.Controllers
{
    public class GroupsController : Controller
    {
        private readonly FootballDbContext dbContext;

        public GroupsController(FootballDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Details(int id)
        {
            Group group = dbContext.Groups.Where(x => x.Id == id)
                .Include(x=>x.Season)
                .ThenInclude(x=>x.Competition)
                .Include(x=>x.Standings)
                .ThenInclude(x=>x.Items).ThenInclude(x=>x.Team)
                .Include(x=>x.Matches).ThenInclude(x=>x.Results).ThenInclude(x=>x.Team)
                .FirstOrDefault();
            if(group == null) { return new NotFoundResult(); }
            GroupViewViewModel viewModel = new GroupViewViewModel();
            viewModel.Id = id;
            viewModel.Standings = group.Standings.FirstOrDefault();
            viewModel.Matches = group.Matches;
            viewModel.Group = group;
            ViewData["Title"] = String.Format("{0} - {1} ({2})", group.Name, group.Season.Name,group.Season.Competition.Name);
            return View(viewModel);
        }
    }
}

FootballWorldWeb/Controllers/SeasonsController.cs
using FootballWorld.Data;
using FootballWorldWeb.Data;
using FootballWorldWeb.Models.Competitions;
using FootballWorldWeb.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FootballWorldWeb.Controllers
{
    public class SeasonsController : Controller
    {
        private readonly ILogger<SeasonsController> _logger;
        private readonly FootballDbContext dbContext;
        private readonly StandingsCalculatorService standingsCalculator;

        public SeasonsController(ILogger<SeasonsController> logger,
            FootballDbContext dbContext, StandingsCalculatorService standingsCalculator)
        {
            _logger = logger;
            this.dbContext = dbContext;
            this.standingsCalculator = standingsCalculator;
        }

        public IActionResult Details(int id,string slug)
        {
            Season season = dbContext.Seasons
                .Include(c => c.Competition)
                .Include(g => g.Groups)
                .ThenInclude(g=>g.GroupTeams).ThenInclude(t=>t.Team)
                .Include(g=>g.Groups)
                .ThenInclude(g => g.Standings)
                .ThenInclude(s => s.Items).ThenInclude(t => t.Team)
                    .Include(g => g.Groups)
                    .ThenInclude(g => g.Matches).ThenInclude(t=>t.Results).ThenInclude(t=>t.Team)
                    .Where(x => x.Id == id)
                    .FirstOrDefault();
                if (season == null) { return new NotFoundResult(); }
                SeasonViewViewModel viewModel = new SeasonViewViewModel();
                viewModel.Season = season;
                viewModel.Competition = season.Competition;
                viewModel.Groups = season.Groups;
                viewModel.SingleGroup = season.Groups.Count > 1 ? false : true;
            viewModel.Lists = season.Groups.Where(x => x.GroupType == GroupType.TeamsList).ToList();
                ViewData["Title"] = String.Format("Season {0} of {1}", viewModel.Season.Name, viewModel.Competition.Name);

                return View(viewModel);
                //todo create view for seasonview//
            }
        }
    }

FootballWorldWeb/Areas/UserPanel/Views/Seasons/Create.cshtml
@model SeasonFormViewModel
<div class="row">
    <div class="col">
        <h2>@ViewData["Title"]</h2>
        <form enctype="multipart/form-data"
              asp-area="UserPanel"
              asp-controller="Seasons"
              asp-action="Create" 
             
              method="post">
            <input type="hidden" asp-for="CompetitionId" />
            <div class="form-group">
                <label class="label" asp-for="Name">
                    Name
                </label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <select class="form-control" asp-for="StartYear"  asp-items="@Model.StartYears"></select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <select class="form-control" asp-for="EndYear" asp-items="@Model.EndYears"></select>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary">
                Create
            </button>
            <a asp-action="Index" class="btn btn-outline-secondary">Back</a>
        </form>
    </div>
</div>

FootballWorldWeb/Areas/UserPanel/Views/Seasons/Edit.cshtml
@model SeasonFormViewModel
<div class="row">
    <div class="col">
        <form enctype="multipart/form-data"
              asp-area="UserPanel"
              asp-controller="Seasons"
              asp-action="Edit"
              method="post">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-group">
                <label class="label" asp-for="Name">
                    Name
                </label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <select class="form-control" asp-for="StartYear" asp-items="@Model.StartYears"></select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <select class="form-control" asp-for="EndYear" asp-items="@Model.EndYears"></select>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary">
                Save
            </button>
            <a asp-action="Index" class="btn btn-outline-secondary">Back</a>
        </form>
        <hr />
        <form asp-area="UserPanel" onsubmit="return confirm('Are you sure?')"
              asp-controller="Seasons"
              asp-action="Delete"
              asp-route-id="@Model.Id"
              method="post">
            <button type="submit" class="btn btn-danger">
                Delete
            </button>
        </form>
    </div>
</div>

FootballWorldWeb/Areas/UserPanel/Views/Seasons/Index.cshtml
@model List<Season>

<div class="row">
    <div class="col">
        <div class="text-left">
            <a asp-action="Create" class="btn btn-xs btn-outline-primary">Add New</a>
        </div>
        <div class="mt-4">
            <h3>Seasons</h3>
        </div>

        <ul class="list-group">
            @foreach (var season in Model)
            {
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-8">
                            @season.Name
                        </div>
                        <div class="col">
                            <a asp-action="Edit" asp-route-id="@season.Id">Edit</a>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

FootballWorldWeb/Areas/UserPanel/Views/Seasons/Overview.cshtml
@model SeasonOverviewViewModel
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col">
                    <h2>Season overview - @Model.Season.Name (@Model.Season.Competition.Name)</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h3>Groups</h3>
                    @if (Model.Season.Groups.Count > 0)
                    {
                        <ul class="list-group">
                            @foreach (var group in Model.Season.Groups.Where(x=>x.GroupType==GroupType.League).ToList())
                            {
                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col">
                                            <form asp-action="Delete" asp-controller="Groups" asp-area="UserPanel" asp-route-id="@group.Id" method="post">
                                                <button class="btn btn-danger btn-xs">
                                                    X
                                                </button>
                                            </form>
                                        </div>
                                        <div class="col">
                                            @group.Name
                                        </div>
                                        <div class="col">
                                            <ul class="list-group">
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Groups" asp-action="Edit" asp-route-id="@group.Id">
                                                        Edit
                                                    </a>
                                                </li>
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Matches" asp-action="Index" asp-route-groupId="@group.Id">
                                                        List Matches
                                                    </a>
                                                </li>
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Groups" asp-action="ManageTeams" asp-route-id="@group.Id">
                                                        Manage Teams
                                                    </a>
                                                </li>
                                                <li class="list-group-item py-0">
                                                    <form 
                                                          asp-controller="Standings"
                                                          asp-action="Update"
                                                          asp-route-groupId="@group.Id"
                                                          method="post">
                                                        <button class="btn btn-primary">Update Standings</button>
                                                    </form>
                                                </li>
                                            </ul>
                                            
                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                <a asp-controller="Groups" asp-action="Create" asp-route-seasonId="@Model.Season.Id" class="btn btn-primary w-100">Add</a>
                    </div>
                <div class="col">
                    <h3>Knockout / Playoffs</h3>

                    @if (Model.Season.Groups.Count > 0)
                    {
                        <ul class="list-group">
                            @foreach (var group in Model.Season.Groups.Where(x => x.GroupType == GroupType.Knockout).ToList())
                            {
                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col">
                                            <form asp-action="Delete" asp-controller="Groups" asp-area="UserPanel" asp-route-id="@group.Id" method="post">
                                                <button class="btn btn-danger btn-xs">
                                                    X
                                                </button>
                                            </form>
                                        </div>
                                        <div class="col">
                                            @group.Name
                                        </div>
                                        <div class="col">
                                            <ul class="list-group">
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Groups" asp-action="Edit" asp-route-id="@group.Id">
                                                        Edit
                                                    </a>
                                                </li>
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Matches" asp-action="Index" asp-route-groupId="@group.Id">
                                                        List Matches
                                                    </a>
                                                </li>
                                                <li class="list-group-item py-0">
                                                    <a asp-controller="Groups" asp-action="ManageTeams" asp-route-id="@group.Id">
                                                        Manage Teams
                                                    </a>
                                                </li>
                                              
                                            </ul>

                                        </div>
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                    <a asp-controller="Groups" asp-action="Create" asp-route-seasonId="@Model.Season.Id" class="btn btn-primary w-100">Add</a>

                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h3>Teams (all)</h3>
                    @if (Model.Teams.Count > 0)
                    {
                        <ul class="list-group">
                            @foreach (var team in Model.Teams)
                            {
                                <li class="list-group-item">@team.Name</li>
                            }
                        </ul>
                    }
                </div>
                <div class="col">
                    <h3>Matches (all)</h3>
                    @if (Model.Matches.Count > 0)
                    {
                        <ul class="list-group">
                            @foreach (var match in Model.Matches)
                            {
                                <li class="list-group-item">@match.Id</li>
                            }
                        </ul>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                <h3>Lists</h3>
                @if (Model.Season.Groups.Count > 0)
                {
                    <ul class="list-group">
                        @foreach (var group in Model.Season.Groups.Where(x => x.GroupType == GroupType.TeamsList).ToList())
                        {
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col">
                                        <form asp-action="Delete" asp-controller="Groups" asp-area="UserPanel" asp-route-id="@group.Id" method="post">
                                            <button class="btn btn-danger btn-xs">
                                                X
                                            </button>
                                        </form>
                                    </div>
                                    <div class="col">
                                        @group.Name
                                    </div>
                                    <div class="col">
                                        <ul class="list-group">
                                            <li class="list-group-item py-0">
                                                <a asp-controller="Groups" asp-action="Edit" asp-route-id="@group.Id">
                                                    Edit
                                                </a>
                                            </li>
                                          
                                            <li class="list-group-item py-0">
                                                <a asp-controller="Groups" asp-action="ManageTeams" asp-route-id="@group.Id">
                                                    Manage Teams
                                                </a>
                                            </li>
                                            <li class="list-group-item py-0">
                                                <form asp-controller="Standings"
                                                      asp-action="Update"
                                                      asp-route-groupId="@group.Id"
                                                      method="post">
                                                    <button class="btn btn-primary">Update Standings</button>
                                                </form>
                                            </li>
                                        </ul>

                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                }
                <a asp-controller="Groups" asp-action="Create" asp-route-seasonId="@Model.Season.Id" class="btn btn-primary w-100">Add</a>
            </div>            </div>
        </div>
    </div>